### PR TITLE
WASM JS unit tests by CI

### PR DESCRIPTION
**Pull request by KaffinPX**
WIP

### CODE REVIEW

**Comment by KaffinPX** [comment]
#154 should be merged first for passing tests

**Comment by michaelsutton** [comment]
Seems extremally outdated, can we close this?

**Comment by aspect** [comment]
I stalled on giving feedback on this as this doesn't really fit the approach we are using in WASM design, which is to use Rust as control mechanism for all functionality, including JavaScript unit tests. 

My policy is to avoid using JavaScript as much as possible, and if not, bias toward JS being injected/created via Rust. This also means that if push comes to shove and we absolutely need NodeJs for tests, we would start a NodeJs instance from within Rust unit tests.

So for now I think this should be closed and I will review and see what needs to be added for this in the coming weeks.

**Comment by michaelsutton** [comment]
Closed as per discussion with @aspect

**Pull request closed without merging**
