### PR TITLE
Move to mimalloc

### PR DESCRIPTION
**Pull request by someone235**
Since rusty-kaspa uses a lot of allocations, the RSS remains high even after the memory is free. This should be mitigated by using mimalloc which utilizes the use of MADV_FREE and MADV_DONTNEED (and equivalent techniques on non unix-like systems) which tend to release memory earlier and help in keeping the RSS small.

### CODE REVIEW

**Comment by elichai** [comment]
Why only unix?

**Comment by michaelsutton** [comment]
1. we should also move the C API call to a more accessible module and should probably set it (the allocator and the `purge_decommits` setting) for tests as well
2. should we leave the version free `version = "*"` @elichai ?

**Comment by elichai** [comment]
> 2. should we leave the version free `version = "*"` @elichai ?

Hmm no, in case some of the API(the C API or the allocator name) changes we don't want our code to just break

**Comment by aspect** [comment]
We don't want any dependencies to be `"*"` as that exposes the project to supply-chain attacks whenever `Cargo.lock` is reset.

**Comment by aspect** [comment]
If mimalloc is to be kept, can its initialization please be moved to `daemon.rs` or better, a dedicated `kaspad/src/memory.rs` module (which is then invoked from `main.rs` via a public fn). If this becomes a requirement for rusty kaspa, it should be loadable externally alongside the daemon itself (with pre-configured parameters within this module/loader fn, not in main).

**Comment by elichai** [comment]
> If mimalloc is to be kept, can its initialization please be moved to `daemon.rs` or better, a dedicated `kaspad/src/memory.rs` module (which is then invoked from `main.rs` via a public fn). If this becomes a requirement for rusty kaspa, it should be loadable externally alongside the daemon itself (with pre-configured parameters within this module/loader fn, not in main).

that might not work well if you have C dependencies, if you want the `override` feature to work properly then mimalloc has to be passed before any C dependency, meaning it should be the first dependency of the top-most crate

Note that this is only for the C deps, for the Rust deps it shouldn't matter where in the dep graph are you setting the global allocator

**Review by elichai — DISMISSED** [review]
LGTM

**Review by michaelsutton — APPROVED** [review]

**Pull request merged**
