### PR TITLE
Address GitHub Actions warnings re Node 20

### PR DESCRIPTION
**Pull request by eladitzhakian**
Issue #469

### CODE REVIEW

**Comment by eladitzhakian** [comment]
hey @coderofstuff can you please allow executing of GH actions so we can test this change?

**Comment by eladitzhakian** [comment]
@coderofstuff thanks. seems there are no more warnings, please review when possible 😄

**Review by aspect — APPROVED** [review]
Many thanks!

**Comment by eladitzhakian** [comment]
> Many thanks!

No problem 😅
Do you guys merge it or do I?
If so it may require another workflow/PR approval

**Review by coderofstuff — APPROVED** [review]
LGTM

**Pull request merged**
